=== manuscriptmastr/coffee-cli/schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "definitions": {
    "aspect": {
      "type": "object",
      "properties": {
        "quantity": {
          "type": "integer",
          "minimum": 1,
          "maximum": 5,
          "description": "On a scale of 1 to 5, how intense was it?"
        },
        "quality": {
          "type": "integer",
          "minimum": 1,
          "maximum": 5,
          "description": "On a scale of 1 to 5, how much did you enjoy it?"
        },
        "notes": {
          "type": "string",
          "default": "",
          "description": "Describe your reaction and any specific notes."
        }
      },
      "required": ["quantity", "quality"]
    }
  },
  "type": "object",
  "properties": {
    "date": {
      "type": "string",
      "description": "The date you brewed this coffee."
    },
    "coffee": {
      "type": "object",
      "properties": {
        "origin": {
          "type": "object",
          "properties": {
            "country": {
              "type": "string",
              "description": "The country, such as 'Ethiopia' or 'Guatemala'"
            },
            "region": {
              "type": "string",
              "description": "The region or coop, such as 'Worka' or 'Nano Challa'."
            }
          },
          "description": "The area in which this coffee was grown.",
          "required": ["country", "region"]
        },
        "roaster": {
          "type": "string",
          "description": "The name of the individual or business who roasted the coffee."
        },
        "roastDate": {
          "type": "string",
          "description": "The date this coffee was roasted."
        }
      },
      "description": "The coffee beans used in your brew.",
      "required": ["origin", "roaster", "roastDate"]
    },
    "ratio": {
      "type": "string",
      "description": "The ration of coffee to water, such as '1:16' or '22g:340g'"
    },
    "grind": {
      "type": "integer",
      "description": "The number of clicks, with zero being when burrs are fully closed."
    },
    "bloomTime": {
      "type": "string",
      "description": "The bloom time."
    },
    "pourTime": {
      "type": "string",
      "description": "The total time from beginning of bloom until a steady stream suddenly falters to separate drops."
    },
    "aroma": {
      "$ref": "#/definitions/aspect",
      "description": "The smell of your brew (low to high), such as 'caramel', 'peach', or 'chocolate'."
    },
    "acidity": {
      "$ref": "#/definitions/aspect",
      "description": "The fruitiness (low to high), such as 'tart', 'crisp', or 'mellow'. Usually indicated by puckering/drying of the tongue or salivation."
    },
    "sweetness": {
      "$ref": "#/definitions/aspect",
      "description": "The sweetness (low to high), such as 'mild', 'deep', or 'rich'. Usually indicated by how 'rounded' the fruit quality is."
    },
    "body": {
      "$ref": "#/definitions/aspect",
      "description": "The texture or mouthfeel (light to heavy), such as 'watery', 'silky', 'syrupy', or 'creamy'."
    },
    "finish": {
      "$ref": "#/definitions/aspect",
      "description": "The aftertaste (short to long), such as 'quick', 'lingering', or 'clean'. Don't rush this aspect."
    },
    "flavor": {
      "type": "string",
      "description": "The overall flavor of this brew, such as 'peach', 'plum', or 'cherry'."
    },
    "score": {
      "type": "integer",
      "minimum": 1,
      "maximum": 10,
      "description": "On a scale of 1 to 10, how much did you enjoy this brew?"
    },
    "notes": {
      "type": "string",
      "default": "",
      "description": "Any additional notes about this brew, such as a faster pour."
    },
    "actionItem": {
      "type": "string",
      "default": "",
      "description": "Any variables to change on the next brew."
    }
  },
  "required": [
    "date",
    "coffee",
    "ratio",
    "grind",
    "bloomTime",
    "pourTime",
    "aroma",
    "acidity",
    "sweetness",
    "body",
    "finish",
    "flavor",
    "score"
  ]
}

=== manuscriptmastr/coffee-cli/entries/08-11-2020.json
{
  "date": "08/11/2020",
  "coffee": {
    "origin": {
      "country": "Ethiopia",
      "region": "Nano Challa"
    },
    "roaster": "Madcap Coffee Company",
    "roastDate": "07/26/2020"
  },
  "ratio": "25g:340g",
  "grind": 25,
  "bloomTime": "0:35",
  "pourTime": "2:33",
  "aroma": {
    "quantity": 2,
    "quality": 4,
    "notes": "Fruity but smooth aroma, with some substance."
  },
  "acidity": {
    "quantity": 4,
    "quality": 4,
    "notes": "Wonderfully rounded lemon, perhaps just a tad sour? The note actually seems to 'bloom' in the mouth."
  },
  "sweetness": {
    "quantity": 3,
    "quality": 3,
    "notes": "Definitely sweeter than other times, but could use more to balance the puckering lemon."
  },
  "body": {
    "quantity": 2,
    "quality": 4,
    "notes" : "Like especially smooth water, almost a light syrup. Could potentially go further."
  },
  "finish": {
    "quantity": 3,
    "quality": 5,
    "notes": "Minty feeling on tip of tongue and teeth."
  },
  "flavor": "None of that especially pointed, puckering lemon zing or any 'off' tastes. This is a very rounded cup — as if the water softened — with the taste blooming and changing over time, then cooling into a minty aftertaste without any weird grassy notes.",
  "score": 8,
  "notes": "Used the Comandante C40 for the first time today. Noticed that the grind looked very coarse but unearthly consistent, like it carved out each tiny pebble. Water drained quickly in bloom phase. Sides of filter were significantly cleaner than with Hario Skerton Pro.",
  "actionItem": "Lower grind to 24 to increase sweetness and body."
}
